# Event Class and sub-classes:  These are the events that may be posted by the
# event listener, and all subsribed listeners may be notified of such events.


class Event:
    """this is a superclass for any events that might be generated by an
    object and sent to the EventManager"""
    def __init__(self):
        self.name = "Generic Event"

class TickEvent(Event):
    def __init__(self):
        self.name = "CPU Tick"

class QuitEvent(Event):
    def __init__(self):
        self.name = "Program Quit"

class CharactorMoveRequest(Event):
    def __init__(self, direction):
        self.name = "Charactor Move Request"
        self.direction = direction

class TogglePauseRequest(Event):
    def __init__(self, pause):
        self.name = "Game Paused/Un-Paused"
        self.pause = pause

class MapBuiltEvent(Event):
    def __init__(self, gameMap):
        self.name = "Map Finished Building"
        self.map = gameMap

class CharactorPlaceEvent(Event):
    """this event occurs when a Charactor is *placed* in a sector,
    ie it doesn't move there from an adjacent sector."""
    def __init__(self, charactor):
        self.name = str(charactor) + " Placement"
        self.charactor = charactor

class CharactorMoveEvent(Event):
    def __init__(self, charactor):
        self.name = str(charactor) + " Move"
        self.charactor = charactor

class GameStartedEvent(Event):
    def __init__(self, game):
        self.name = "Game Started"
        self.game = game

class GameClockEvent(Event):
    def __init__(self, game):
        self.name = "Game Clock Tick"
        self.game = game

class CharactorCollisionEvent(Event):
    def __init__(self, colliders):
        self.tempName = ""
        self.name = ""
        for i in range(len(colliders)-1):
            self.tempName = str(colliders[i].charactor) + " - "
            self.name = self.name + self.tempName
        self.name = self.name + str(colliders[len(colliders)-1].charactor) + " Collision"
        self.colliders = colliders

        
if __name__ == "__main__":
	print("wasn't expecting that")
